# embed_file.cmake — bundle a single file into a generated C++ header.
#
# Invoked from CMakeLists.txt via `cmake -P` as a custom command. Reads
# INPUT_FILE and emits OUT_HEADER containing a constexpr byte array
# named SYMBOL plus a `SYMBOL ## Size` size constant. Both live at file
# scope; the header is meant to be included exactly once.
#
# Usage:
#   cmake -DINPUT_FILE=... -DOUT_HEADER=... -DSYMBOL=... -P embed_file.cmake

if(NOT INPUT_FILE)
    message(FATAL_ERROR "embed_file.cmake: INPUT_FILE required")
endif()
if(NOT OUT_HEADER)
    message(FATAL_ERROR "embed_file.cmake: OUT_HEADER required")
endif()
if(NOT SYMBOL)
    message(FATAL_ERROR "embed_file.cmake: SYMBOL required")
endif()

file(READ "${INPUT_FILE}" CONTENT_HEX HEX)
string(LENGTH "${CONTENT_HEX}" HEX_LEN)
math(EXPR FILE_SIZE "${HEX_LEN} / 2")

# Convert hex string to comma-separated byte literals. 16 bytes per
# line keeps the generated header readable.
set(BYTES "")
set(COL 0)
set(POS 0)
while(POS LESS HEX_LEN)
    string(SUBSTRING "${CONTENT_HEX}" ${POS} 2 BYTE)
    if(COL EQUAL 0)
        string(APPEND BYTES "    ")
    endif()
    string(APPEND BYTES "0x${BYTE},")
    math(EXPR POS "${POS} + 2")
    math(EXPR COL "${COL} + 1")
    if(COL EQUAL 16)
        string(APPEND BYTES "\n")
        set(COL 0)
    else()
        string(APPEND BYTES " ")
    endif()
endwhile()
if(NOT COL EQUAL 0)
    string(APPEND BYTES "\n")
endif()

set(HEADER_CONTENT "// Auto-generated by embed_file.cmake — do not edit.
// Source: ${INPUT_FILE}

#pragma once

#include <cstddef>

static constexpr unsigned char ${SYMBOL}[] = {
${BYTES}};
static constexpr size_t ${SYMBOL}Size = sizeof(${SYMBOL});
")

file(WRITE "${OUT_HEADER}" "${HEADER_CONTENT}")
message(STATUS "embed_file: wrote ${OUT_HEADER} (${FILE_SIZE} bytes)")
